# NumPy Tutorial

----

## NumPy Introduction

NumPy is the **core library for scientific computing** in Python. The central object in the NumPy library is the NumPy array. The NumPy array is a **high-performance multidimensional array object**, which is designed specifically to perform math operations, **linear algebra**, and probability calculations. Using a NumPy array is usually a lot faster and needs less code than using a Python list. A huge part of the NumPy library consists of C code with the Python API serving as a wrapper around these C functions. This is one of the reasons why NumPy is so fast.



![numpy logo](https://www.freecodecamp.org/news/content/images/2020/07/numpy.png)

---

#### Table of contents
1. Installing NumPy
2. NumPy array
3. Essential methods
4. Multidimensional (nd) Arrays
5. Reshaping
6. Generating Arrays

---

## 1. Installing NumPy

The only prerequisite for installing NumPy is **Python** itself. If you don’t have Python yet and want the simplest way to get started, we recommend you use the [***Anaconda Distribution***](https://www.anaconda.com/distribution) - it includes Python, NumPy, and many other commonly used packages for scientific computing and data science.

NumPy can be installed with *conda*, with *pip*, with a package manager on macOS and Linux, or from source.


### CONDA

`conda create -n my-env
conda activate my-env`

`conda install numpy`

### PIP

`pip install numpy`

### Import NumPy:

In [1]:
import numpy as np

In [2]:
#check version
np.__version__

'1.19.1'

--- 

## 2. NumPy array

In [3]:
a = np.array([1,2,3,4,5])

In [4]:
a

array([1, 2, 3, 4, 5])

In [5]:
a.shape   # shape of the array

(5,)

In [6]:
a.dtype   # type of the elements

dtype('int64')

In [7]:
a.ndim    # number of dimensions

1

In [8]:
a.size    # total number of elements

5

---

## 3. Essential methods:

In [9]:
b = np.array([1,2,3])

##### Access and change elements:

In [10]:
b[0]         # Access elements

1

In [11]:
b[0] = 5     #change elements

In [12]:
b

array([5, 2, 3])

##### Elementwise math operations

In [13]:
b * np.array([2,0,2])

array([10,  0,  6])

In [14]:
b.sum()

10

---

## 4. Multidimensional (nd) Arrays

In [15]:
c = np.array([[1,2], [3,4]])

In [16]:
c

array([[1, 2],
       [3, 4]])

In [17]:
c.shape

(2, 2)

##### Access elements

In [18]:
c[0]

array([1, 2])

In [19]:
c[0,0]   # row first, then columns

1

##### Transpose 

In [20]:
c.T

array([[1, 3],
       [2, 4]])

![transpose](transpose1.png)

---

##### Matrix multiplication

![DotProductVsElementWise](DotProductVsElementWise2.jpg)

In [21]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [22]:
b = np.array([[3, 4], [5,6]])
b

array([[3, 4],
       [5, 6]])

In [23]:
a * b        # elementwise multiplication

array([[ 3,  8],
       [15, 24]])

In [24]:
a.dot(b)     # dot product - inner dimensions must match

array([[13, 16],
       [29, 36]])

##### Determinant

In [25]:
np.linalg.det(a)

-2.0000000000000004

##### Inverse

In [26]:
np.linalg.inv(a)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

---

## 5. Reshaping

In [27]:
a = np.arange(1, 7)
a

array([1, 2, 3, 4, 5, 6])

In [28]:
a.reshape((2, 3))

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
a.reshape((2, 4))     # error if shape cannot be used

ValueError: cannot reshape array of size 6 into shape (2,4)

---

## 6. Generating Arrays

##### zeros

In [30]:
np.zeros((2,3))     # size as tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

##### ones

In [31]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

##### Specific value

In [32]:
np.full((3,3),5.0)

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

##### Arange

In [33]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### Linspace

In [34]:
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

---

---

# Thanks!
#### FOR YOUR ATTENTION